version: '3.7'

services:
  php:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal
